---
- name: Setup LAMP stack on Ubuntu Server
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Install PHP and common extensions
      apt:
        name:
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
        state: present

    - name: Install MySQL Server (MariaDB)
      apt:
        name: mariadb-server
        state: present

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Ensure MySQL is running and enabled
      service:
        name: mariadb
        state: started
        enabled: yes
